name: CI

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - 'src/pages/api/binder*/**'
      - 'ops/manifests/**'
      - 'docs/**'
      - '**.md'
  pull_request:
    branches:
      - main
      - develop
    paths-ignore:
      - 'src/pages/api/binder*/**'
      - 'ops/manifests/**'
      - 'docs/**'
      - '**.md'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    # Skip if commit message contains [skip ci]
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run type check
        run: npm run typecheck
        continue-on-error: true
      
      - name: Run linter
        run: npm run lint
        continue-on-error: true
      
      - name: Run tests
        run: npm test
        continue-on-error: true
      
      - name: Build
        run: npm run build
        continue-on-error: true

  lint:
    name: Lint
    runs-on: ubuntu-latest
    
    # Skip if commit message contains [skip ci]
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run ESLint
        run: npm run lint
        continue-on-error: true

  typecheck:
    name: Type Check
    runs-on: ubuntu-latest
    
    # Skip if commit message contains [skip ci]
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run TypeScript check
        run: npm run typecheck
        continue-on-error: true

